# Generated by Django 4.2.2 on 2024-01-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='code',
        ),
    ]
